In [1]:
import numpy as np
from analyzer import Analyzer

words = ["apple", "elephant", "tomato", "onion", "nagoya", "nation", "tiny", "education", "at", "tickle"]

In [2]:
init_mat = np.array([0])
max_mat = np.array([len(words)+1])

def next_func(mat):
    if mat[0] == 0:
        for i in range(len(words)):
            yield np.array([i+1])
    else:
        now = words[mat[0]-1]
        for i, word in enumerate(words):
            if now[-1] == word[0]:
                yield np.array([i+1])

In [3]:
an = Analyzer(init_mat, max_mat, next_func, default=-1)
an.alpha_beta_analyze()
an.retrograde_analyze()
print(an.eval_list)
print(an.step_list)


--- start alpha beta analyze ---


-- alpha beta analyze finished --

total detected states = 11
total elapsed time = 0.000
next, apply retrograde_analyze to the states that could not be evaluated

--- start retrograde analyze ---


-- retrograde analyze finished --

total elapsed time = 0.000
analyze finished, You can use 'mat_to_status' or 'list_example' etc. to get the results of analysis.
[1, 0, 1, -2, -2, 0, 0, -1, 0, 1, 0]
[1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0]


In [4]:
init_mat = np.array([0, len(words)])
max_mat = np.array([1<<len(words), len(words)+1])

def next_func(mat):
    if mat[1] == len(words):
        for i in range(len(words)):
            yield np.array([1<<i, i])
    else:
        now = words[mat[1]]
        for i, word in enumerate(words):
            if mat[0] & (1<<i): continue
            if now[-1] == word[0]:
                yield np.array([mat[0]+(1<<i), i])

In [5]:
an1 = Analyzer(init_mat, max_mat, next_func, default=-1)
an1.alpha_beta_analyze(rel_depth=100)
an1.retrograde_analyze()
print(an1.eval_list)
print(an1.step_list)


--- start alpha beta analyze ---


-- alpha beta analyze finished --

total detected states = 291
total elapsed time = 0.005
next, apply retrograde_analyze to the states that could not be evaluated

--- start retrograde analyze ---


-- retrograde analyze finished --

total elapsed time = 0.000
analyze finished, You can use 'mat_to_status' or 'list_example' etc. to get the results of analysis.
[1, -1, 1, 1, -1, 1, 1, -1, 1, 1, -1, 1, 1, 1, -1, 1, -1, 1, 1, -1, -1, 1, 1, -1, -1, -1, 1, -1, -1, 1, -1, 1, -1, -1, 1, -1, 1, -1, -1, 1, 1, -1, 1, 1, -1, -1, -1, 1, -1, 1, 1, -1, -1, 1, 1, 1, -1, 1, -1, 1, 1, -1, -1, -1, 1, -1, -1, 1, -1, 1, -1, -1, 1, 1, -1, 1, -1, -1, 1, -1, 1, 1, -1, 1, 1, -1, -1, 1, -1, 1, 1, -1, -1, -1, 1, -1, 1, -1, 1, 1, -1, -1, 1, 1, -1, -1, -1, 1, 1, -1, -1, -1, -1, 1, -1, -1, -1, 1, -1, -1, 1, -1, 1, -1, 1, -1, -1, -1, 1, -1, -1, 1, 1, 1, -1, 1, 1, -1, 1, -1, -1, -1, 1, -1, 1, -1, 1, -1, -1, -1, 1, -1, -1, -1, 1, 1, -1, -1, -1, 1, -1, 1, -1, 1, 1, -1, -1, -1, -1, 1,

In [6]:
max_mat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
init_mat = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
])

an = Analyzer(init_mat, max_mat, next_func)

for mat in an.sym_func(init_mat):
    print(mat)
    print()

[[0 1 2]
 [3 4 5]
 [6 7 8]]

